services:
  gh-code:
    image: gh-code
    build:
      context: ${LOCAL_WORKSPACE_FOLDER:-.}
      dockerfile: Dockerfile
    ports:
      - "2222:22"
    volumes:
      - ${PWD}:/workdir
      - ${HOME}/.ssh/id_ed25519.pub:/home/vscode/.ssh/authorized_keys:ro
