#!/bin/sh
set -e

TOP=$(dirname "$0")

if [ -z "$1" ]; then
  echo "Usage:"
  echo "$0 build    # Build for docker image" 
  echo "$0 shell    # Login docker" 
  echo "$0 .        # Open Visual Studio Code with Dev Container"

  exit 1
fi


if [ $1 = "build" ]; then
  docker compose -f ${TOP}/docker-compose.yml build
  exit 0
fi

if [ $1 = "shell" ]; then
  docker compose -f ${TOP}/docker-compose.yml run --name gh-code -it --rm  gh-code
  exit 0
fi

if [ $1 = "." ]; then
  # コンテナ名gh-code をHEX(67682d636f6465)に変換
  HEX=$(printf '%s' 'gh-code' | xxd -p | tr -d '\n')
  code --folder-uri "vscode-remote://attached-container+${HEX}/workdir/"
fi

echo "Unknown command: $1"
echo "Usage: $0 build|shell"
exit 1


